basePath: /
host: localhost:5000
info:
  contact: {}
  description: API Gateway for QoS Assurance of Open API Based Application
  title: OAG(Open API Gateway)
  version: "1.0"
paths:
  /forestFires:
    get:
      consumes:
      - text/html
      description: Get forestFires data.
      produces:
      - text/html
      responses:
        "200":
          description: ok
          schema:
            type: string
  /forestPoint:
    get:
      consumes:
      - text/html
      description: Get forestPoint data.
      produces:
      - text/html
      responses:
        "200":
          description: ok
          schema:
            type: string
  /forestfire:
    get:
      consumes:
      - text/html
      - application/xhtml+xml
      - application/xml;q=0.9
      - image/avif
      - image/webp
      - image/apng
      - '*/*;q=0.8'
      - application/signed-exchange;v=b3;q=0.9
      description: Get forestfire data.
      produces:
      - text/html
      responses:
        "200":
          description: ok
          schema:
            type: string
swagger: "2.0"
